// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mprsafugfkgapgolimjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcnNhZnVnZmtnYXBnb2xpbWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDI5OTcsImV4cCI6MjA2NTYxODk5N30.mw8zHd84vQedaajsTHJZyX5FzcMy_ohxsMk8rRF5Zkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);